### ISSUE TITLE
rails3 support?

### ISSUE THREAD

**Issue by 29decibel** [martinrehfeld/ext_scaffold#1]
is this plugin supported in rails3
i got an error "ext_scaffold generator not found" while i am using it in rails3

**Comment by martinrehfeld** [comment]
Hi there!

ext_scaffold is in no way adapted to Rails 3. The generated code will probably continue to work -- I will claim this until someone proves me wrong, that is.

Anyhow, feel free to fork and hack away...

Cheers,
Martin
