### ISSUE TITLE
Could not find generator ext_scaffold. 

### ISSUE THREAD

**Issue by rendier** [martinrehfeld/ext_scaffold#2]
Hi,

I keep getting the following error:
Could not find generator ext_scaffold.
when I try to generate a class using ext js 3.3.1 and RoR 3.0.3.

Is this a problem with RoR 3?  Will it be fixed?

**Comment by martinrehfeld** [comment]
Ext_scaffold has not been adapted to Rails3 -- I do not have any plans on doing so. The generated code should continue to work the Rails3, though.
